version: '3.8'
services:
  web:
    image: sreejitha1996/web_container:web1  # Your custom web image
    container_name: web_container
    ports:
      - "8080:80"  # Expose container's port 80 to host's port 8080
    environment:
      - DB_HOST=mysql  # MySQL service name in docker-compose
      - DB_PORT=3306
      - DB_NAME=app_db
      - DB_USER=app_user
      - DB_PASSWORD=app_password
    depends_on:
      - mysql

  mysql:
    image: sreejitha1996/mysql:8  # Your MySQL image
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
