version: '3.8'

services:
  web:
    image: sreejitha1996/web_container:web1  # Pull the web image from Docker Hub
    container_name: web_container
    ports:
      - "8010:5000"  # Expose port 80 from the container to port 8080 on host
    environment:
      - DB_HOST=mysql_container  # Point to MySQL service by container name
      - DB_PORT=3306  # MySQL default port
      - DB_NAME=app_db  # The name of your database
      - DB_USER=app_user  # The MySQL username
      - DB_PASSWORD=app_password  # The MySQL user password
    depends_on:
      - mysql  # Ensure the web container starts after the MySQL container is up

  mysql:
    image: mysql:8  # Pull the MySQL image from Docker Hub
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # MySQL root password
      - MYSQL_DATABASE=app_db  # The database to be created
      - MYSQL_USER=app_user  # MySQL user to be created
      - MYSQL_PASSWORD=app_password  # Password for app_user
    ports:
      - "3306:3306"  # Expose port 3306 for MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data across container restarts

volumes:
  mysql_data:
    driver: local  # Use local storage for persisting MySQL data
